<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penilai_model extends CI_Model
{

    public $table = 'penilai';
    public $id = 'id_penilai';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->query("select * from penilai")->result();
        // return $this->db->get($this->table)->result();

    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function laporan_penilai($nip_penilai)
    {
        $this->db->where('nip_penilai', $nip_penilai);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('id_penilai', $q);
	$this->db->or_like('nip_penilai', $q);
	$this->db->or_like('nama', $q);
    $this->db->or_like('pangkat', $q);
    $this->db->or_like('golongan', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('keterangan', $q);
	
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_penilai', $q);
    $this->db->or_like('nip_penilai', $q);
    $this->db->or_like('nama', $q);
    $this->db->or_like('pangkat', $q);
    $this->db->or_like('golongan', $q);
    $this->db->or_like('status', $q);
    $this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        // $this->db->insert('pegawai',$data);
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kepsek_model.php */
/* Location: ./application/models/Kepsek_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-18 06:23:46 */
/* http://harviacode.com */